project:
  type: book

book:
  title: "Introduction to Computational Psychology"
  author: "Alan Jern"
  date: last-modified
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-bayes.qmd
  description: |
      An introduction to computational cognitive science with a focus on 
      probabilistic modeling. Code and exercises in Python.
  repo-actions: source
  repo-url: https://alanjern.github.io/computational-psych-book/

bibliography: references.bib

format:
  html:
    theme: pulse
  pdf:
    documentclass: scrreprt

editor: visual

